Django_Project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

#    아무것도 안쓰고 서버 페이지 접속하면 admin로 접속
urlpatterns = [
    path("admin/", admin.site.urls),
    path('final4/', include('final4.urls')),
    path('', include('single_pages.urls')),
    path('blog/', include('blog.urls')),  # blog  라고 쓰면 어디로 접속되게 할 건지
    path('midterm/', include('midterm.urls')),
    path('accounts/', include('allauth.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('search/<str:q>/', views.PostSearch.as_view()),
    path('', views.PostList.as_view()), # server/blog => 모든 걸 검색
    path('<int:pk>/new_comment/', views.new_comment),# /blog/1/new_comment/
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()), # blog/update_comment/1
    path('delete_comment/<int:pk>/', views.delete_comment), # blog/delete_comment/1

    path('<int:pk>/', views.PostDetail.as_view()), # server/blog/1 => 키로 하나만 검 => 지정 안하면 자동으로 Post_detail파일을 찾게됨
    path('category/<str:slug>/', views.category_page), # function 형태로 가장 , slug가 따라옴 -> views 함수에 slug 매개변수 추가
    path('create_post/', views.PostCreate.as_view()), # /blog/create_post/
    path('update_post/<int:pk>/', views.PostUpdate.as_view()) # /blog/update_post/1

    #   path('<int:pk>/', views.single_post_page), #server/blog/1
    #   path('update_post/<int:pk>/', views.PostUpdate.as_view()),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
import os

#   모델 변경하면 마이그레이션하기 !!!
#   카테고리에서 똑같이 따오셈
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # 문자열은 f''로 넘김 / 고유 URL 부여하기
        return f'/blog/category/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Categories'
        #   화면 상에 보여지는 이름 설정


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)
    content = models.TextField()

    #   헤드 이미지랑 파일 업로드 만들기
    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d', blank=True)
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d', blank=True)

    #   자동으로 작성시각과 수정시각 저장하기
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #   on_delete = models.CASCADE 작성자 지우면 게시글도 지워짐 / blank=False니까 무조건 선택 해야됨
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    #   선택 안 해도 됨
    #   One To Many 관계
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    #   Many to Many 관계 - 자동으로 null됨
    tags = models.ManyToManyField(Tag, blank=True)

    #   제목에 포스트 번호와 제목 보여주기
    def __str__(self):
        return f'[{self.pk}] {self.title}   ::  {self.author}'

    def get_absolute_url(self):  # 문자열은 f''로 넘김 / 고유 URL 부여하기
        return f'/blog/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]
        # [-1] => 맨 뒤에 있는 확장자가 됨

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField() # 사용자가 작성하는 것은 이것 뿐
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'
        # 댓글들, detail에서도 고유 번호를 부여하도록 함

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',) # 필드를 뭘로 쓸거냐

blog/views.py
from django.shortcuts import render, redirect
from .models import Post, Category, Comment
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q


# models.py안에 Post 만들어 놓음
# Create your views here

# def : FBV (return render) / class : CBV - as_viewn (model = Post)

# templates : user
# 함수 : request.user
# 클래스 : self.request.user

def csrf_failure(request, reason=""):
    return redirect('/blog/')
    # 토큰 오류 방지 / 404 forbidden


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category', 'tags']

    # template_name = "blog/post_update_form.html"
    # default templated_name => post_form.html
    template_name = 'blog/post_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class PostCreate(LoginRequiredMixin, UserPassesTestMixin,
                 CreateView):  # Form 지원 / Form Class / form이긴 하지만 view를 상속 받아서 만든거임
    model = Post
    # post model에 있는 변수명이랑 똑같이 해주면 댐
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category', 'tags']

    # blog/create_post 들어가면 post_form.html찾음
    # template_name = 'blog/post_form.html'

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user  # 로그인 되어잇는 사용자
            # not tag
            return super(PostCreate, self).form_valid(form)
        else:
            return redirect('/blog/')


class PostList(ListView):
    # post_list 가 변수가 됨 여기에 리스트를 전부 가져오겠다는 거임 / pk 역순으로 / postlist형태로 자동으로 넘어감
    # CBV 방식
    model = Post  # post_list 변수
    ordering = '-pk'
    paginate_by = 2  # 알아서 한 페이지 당 두개씩 보이게 해줌

    # 추가 context-Category 해서 넘겨줌 => detail도 마찬가지
    # template_name = 'blog/old_post_list.html' =>    대신 index.html를 post_list.html로 바꿔주면 됨
    # urls.py에서 views.py 호출 해줌
    # 자동으로 모델명_list.html를 찾도록 강제적으로 명령되어있음
    # 수동으로 조정해줄 수 있음

    def get_context_data(self, **kwargs):
        # listview에서 자동으로 부름 -> post_list가 자동으로 넘어감
        context = super(PostList, self).get_context_data()

        # 카테고리 테이블에 들어있는 데이터를 카테고리즈 라는 변수에 넣어서 넘겨라
        context['categories'] = Category.objects.all()

        # post에서 카테고리가 없는 것의 개수를 가져오자 -> 1개면 1이라는 숫자를 노카테고리 포스트 카운트에 저장
        context['no_category_post_count'] = Post.objects.filter(category=None).count()

        # 이게자동으로 post_list.html에 넘어감 , { post_list, categories, no_category_post_count }  = { 7, 4, 1 } / 포스트개수 , 카테고리 분류, 미분류개수
        return context


class PostDetail(DetailView):  # post_detail.html을 자동적으로 찾게 됨
    model = Post

    #   template_name = 'blog/single_post_page.html'

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()  # post 라는 하나의 값만 넘어감 , post
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        context['comment_form'] = CommentForm
        return context


def category_page(request, slug):
    if slug == 'no_category':  # /blog/category/no_category/
        category = "No Category"
        post_list = Post.objects.filter(category=None)
    else:  # /blog/category/slug(프로그래밍, 문화-예술, 라이프스타일)
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    return render(
        request,
        'blog/post_list.html',
        {
            'post_list': post_list,
            'categories': Category.objects.all(),
            'no_category_post_count': Post.objects.filter(category=None).count(),
            'category': category,  # 현재 분류 카테고리를 카테고리에 넣어서 보내
        }
    )


# comment
def new_comment(request, pk):
    if request.user.is_authenticated:
        # 하나의 객체만 가져오는 함수가 작성되어 있으니까 그걸 이용하자, Post모델에서 번호에 해당되는 한개만 가져오자
        post = get_object_or_404(Post, pk=pk)
        if request.method == "POST":
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)  # 임시저장
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied


def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    # 로그인 + 댓글 삭제 요청한 사람 == 댓글 작성자 본인이면 댓글 삭제 가능
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied


class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment  # 다섯개나 갖고 있음 -> CommentForm을 만들어놨으니 그걸 가져다 쓰자, Cotent하나 있음
    form_class = CommentForm

    # templates => comment_form.html

    # POST 방식인지 GET 방식인지 확인하는 함수
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:  # get_object : Comment
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class PostSearch(PostList):
    paginate_by = None  # PostList에서 지정했던 페이지네이션은 필요없으므로 None으로 지정

    def get_queryset(self):
        q = self.kwargs['q'] # urls.py에서 인자로 받아온 값을 가져올 때 사용
        post_list = Post.objects.filter(
            Q(title__contains=1) | Q(tags__name__contains=q) # 여러 조건을 사용하고 싶을 때 Q 사용 / tag__name__contains == tag.name.contains
        ).distinct() # 중복 제거
        return post_list

    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'

        return context

# 얘 대신 위에 클래스로 이용해바 ~
# FBV 방식
# def index(request):
#     #   포스팅 되어있는 하나하나가 object임 / DB에 있는 거 가져옴 / pk의 역순으로 가져와라
#     posts = Post.objects.all().order_by('-pk')
#
#     return render(
#         request,
#         'blog/old_post_list.html',
#         #   데이터 넘길 땐 {} 중괄호로 / 앞: (index.html로 넘기는)변수명 지정 / 뒤: 위에서 오브젝트 받았던 리스트
#         {
#             'posts': posts,
#         }
#     )
#
# def single_post_page(request, pk):
#     post = Post.objects.get(pk=pk) #데이터 베이스 가서 하나만 가져와
#     return render(
#         request,
#         'blog/single_post_page.html',
#         {
#             'post': post,
#         }
#     )

final4/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView,DetailView
from .models import Product, Sale
from .forms import ProductForm
from django.shortcuts import get_object_or_404
from django.core.exceptions import PermissionDenied

# Create your views here.

def index(request):
    return render(
        request,
        'final4/index.html'
    )

class ProductList(ListView):
    model = Product
    ordering = '-pk'
    paginate_by = 3
    template_name = 'final4/product_list.html'

    def get_context_data(self, **kwargs):
        context = super(ProductList, self).get_context_data()
        return context

class ProductDetail(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super(ProductDetail, self).get_context_data()  # post 라는 하나의 값만 넘어감 , post
        context['product_form'] = ProductForm
        return context

def buyProduct(request, pk):
    if request.user.is_authenticated:
        # 하나의 객체만 가져오는 함수가 작성되어 있으니까 그걸 이용하자, Post모델에서 번호에 해당되는 한개만 가져오자
        product = get_object_or_404(Product, pk=pk)

        if request.method == 'POST':
            product_form = ProductForm(request.POST)
            if product_form.is_valid():
                Sale = product_form.save(commit=False)  # 임시저장
                Sale.product = product
                Sale.user = request.user
                Sale.save()
                return redirect(Product.get_absolute_url())
        else:
            return redirect(Product.get_absolute_url())
    else:
        raise PermissionDenied

class CartList(ListView):
    model = Sale
    template_name = 'final4/sale_list.html'

    def get_context_data(self, **kwargs):
        context = super(CartList, self).get_context_data()  # post 라는 하나의 값만 넘어감 , post
        context['product_name'] = Sale.objects.all()
        context['product_form'] = ProductForm
        context['sale_name'] = Sale.product
        context['sale_count'] = Sale.count
        return context

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}Blog{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'blog/bootstrap4/bootstrap.min.css' %}" media="screen">

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
            integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
            crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/89a12d4a7e.js" crossorigin="anonymous"></script>

</head>

<body>
{% include 'blog/navbar.html' %}

<!-- main post -->
<div class="container my-3" id='main-area'>
    <div class="row">
        <div class="col-md-8 col-lg-9">

            {% block main_content %} <!--비워두고 여기를 채우는 거임-->
            {% endblock %}

        </div>

        <div class="col-md-4 col-lg-3">

            <!-- Search widget-->
            <div class="card mb-4">
                <div class="card-header">Search</div>
                <div class="card-body">
                    <div class="input-group">
                        <input id="search-input" class="form-control" type="text" placeholder="Enter search term..."
                               aria-label="Enter search term..." aria-describedby="button-search"/>
                        <!-- 누르면 searchPost() 함수 호출 -->
                        <button onclick="searchPost();" class="btn btn-primary" id="button-search" type="button">Go!</button>
                    </div>
                </div>
            </div>

            <!-- Categories widget-->
            <div class="card mb-4" id="categories-card">
                <div class="card-header">Categories</div>
                <div class="card-body">
                    <div class="row">
                        <ul>
                            <!-- {{ no_category_post_count }} 미분류 카테고리 출력-->
                            {% for category in categories %}
                                <li>
                                    <a href="{{ category.get_absolute_url }}">{{ category }} ({{ category.post_set.count }})</a>
                                </li>
                            {% endfor %}
                                <li>
                                    <a href="/blog/category/no_category/">No Category ({{ no_category_post_count }})</a>
                                </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'blog/footer.html' %}

<script>
    function searchPost(){
        let searchValue = document.getElementById("search-input").value.trim()
        if ( searchValue.length > 1 ){
            location.href = "/blog/search/" + searchValue + "/";
        }
        else {
            alert("검색어(" + searchValue + ")가 너무 짧습니다.");
        }
    };

    document.getElementById("search-input").addEventListener("keyup", function(event){
        if(event.key === "Enter"){
            searchPost();
        }
    });
</script>

</body>
</html>

blog/templates/blog/base_full_width.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}Blog{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'blog/bootstrap4/bootstrap.min.css' %}" media="screen">

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
            integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
            crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/89a12d4a7e.js" crossorigin="anonymous"></script>

</head>

<body>
{% include 'blog/navbar.html' %}

<!-- main post -->
<div class="container my-3">
    <div class="row">
        <div class="col-12" id="main-area">

            {% block main_content %} <!--비워두고 여기를 채우는 거임-->
            {% endblock %}

        </div>
    </div>
</div>

{% include 'blog/footer.html' %}

</body>
</html>

blog/templates/blog/comment_form.html
    {% extends 'blog/base_full_width.html' %}

    {% load crispy_forms_tags %}

    {% block head_title %}Edit Comment - Blog{% endblock %}

    {% block main_content %}
        <h1>⭐️Edit Comment⭐️️</h1> <!--하나짜리 form으로 정상작동함-->
        <hr/>
        <form method="post" enctype="multipart/form-data">{% csrf_token %} <!--파일 첨부 있으면 enctype 있어야됨 파일 없으면 이거 없어도 ㄱㅊ-->
                {{ form | crispy }}
            <button type="submit" class="btn btn-primary float-right">Submit</button>
        </form>
    {% endblock %}

blog/templates/blog/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; SUJI Website 2022</p></div>
</footer>

blog/templates/blog/old_post_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blog</title>
</head>
<body>
    <nav>
        <a href="/">Home</a>
    </nav>
    <h2>Post List</h2>
    <!--Python 쓸 때는 중괄호로-->
    {% for p in post_list %}    <!--post_list라고 자동으로 변수를 넘겨줌-->
    <hr/>
    <!--href="{{p.pk}}" 로 쉽게 해도됨-->
    <h3><a href="{{ p.get_absolute_url }}/"> {{ p.title }} </a></h3>
    <p>{{p.created_at}}</p>
    <p>{{p.content}}</p> <!--model.py에 썼던 변수명과 동일하게 써야됨-->
    {% endfor %}
</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ post.title }} - Blog
{% endblock %}

{% block main_content %}
<!-- 하나의 post니까 p가 아니라 post 사용 -->
<!-- Post content-->
<article>
    <div id="post-area">
        <!-- Post header-->
        <header class="mb-4">
            <!-- Post title-->
            <h1 class="fw-bolder mb-1" id="title">{{ post.title }}</h1>
            <h5 class="text-muted">{{ post.hook_text }}</h5>
            <!-- Post meta content-->
            <div class="text-muted fst-italic mb-2">Posted on {{ post.created_at }}
                by <a href="#">{{ post.author | upper }}</a></div>

            <!-- 로그인 + 글 작성자만 글 수정 가능 -->
            {% if user.is_authenticated and user == post.author %}
            <a class="btn btn-info btn-sm float-right" href="/blog/update_post/{{ post.pk }}/" role="button">
                <i class="fas fa-pen"></i>&nbsp;&nbsp;Edit Post
            </a>
            {% endif %}

            <!-- Post categories-->
            {% if post.category %}
            <span class="badge badge-secondary">{{ post.category }}</span>
            {% else %}
            <span class="badge badge-secondary">미분류</span>
            {% endif %}
        </header>

        <!-- Preview image figure-->
        <figure class="mb-4">
            {% if post.head_image %}
            <img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="{{ post.title }} head image"/>
            {% else %}
            <img class="img-fluid rounded" src="https://picsum.photos/seed/{{post.id}}/800/200" alt="random image"/>
            {% endif %}
        </figure>

        <!-- Post content-->
        <section class="mb-5">
            <p class="fs-5 mb-4">{{ post.content | linebreaksbr }}</p>

            <!--tag area-->
            {% if post.tags.exists %}
            <i class="fas fa-tags"></i>
            {% for tag in post.tags.all %}
            <span class="badge badge-pill badge-light">{{ tag }}</span>
            {% endfor %}
            <br/><br/>
            {% endif %}

            {% if post.file_upload %}
            <a href="{{ post.file_upload.url }}" class="btn btn-outline-dark" role="button" download>Download:
                {% if post.get_file_ext == 'csv' %}
                <i class="fas fa-file-cvs"></i>
                {% elif post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                <i class="fas fa-file-excel"></i>
                {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
                <i class="fas fa-file-word"></i>
                {% else %}
                <i class="fas fa-file"></i>
                {% endif %}
                {{ post.get_file_name }} <!-- model에 함수 추가 -->
            </a>
            {% endif %}
        </section>
    </div>
</article>

<section class="mb-5">
    <div id="comment-area">
        <!-- Comment form -->
        <div class="card bg-light">
            <div class="card-header">Leave a Comment</div>
            <div class="card-body">
                {% if user.is_authenticated %} <!-- 로그인이 되어 있으면 -->
                <form class="mb-4" id="comment-form" method="POST" action="{{ post.get_absolute_url }}new_comment/">
                    {% csrf_token %} <!--장고에서 제공하는 토큰 / form안에 넣어야됨!!-->
                    <div class="form-group">
                        {{ comment_form | crispy }} <!-- view에서 detail 클래스에서 보여줌 (comment_form을 context에 담아서 보내줌 ) -->
                    </div>
                    <button type="submit" class="btn btn-primary float-right">Submit</button>
                </form>
                {% else %}
                <a role="button" class="btn btn-outline-dark btn-block btn-sm"
                   href="#" data-toggle="modal" data-target="#loginModal">Log In and leave a comment</a>
                {% endif %}
            </div>
        </div>

        <div class="card bg-light">
            <div class="card-body">
                {% if post.comment_set.exists %}
                    {% for comment in post.comment_set.iterator %}
                    <!-- Single comment-->
                    <div class="d-flex mb-4" id="comment-{{ comment.pk }}">
                        <div class="flex-shrink-0">
                            <img class="rounded-circle"
                                 src="https://dummyimage.com/50x50/ced4da/6c757d.jpg&text={{ comment.author.username }}"
                                 alt="..."/>
                        </div>
                        <div class="media-body"> <!-- 교수님 : ms-3 -->
                            {% if user.is_authenticated and comment.author == user %}
                            <!-- 댓글 수정하기 -->
                            <div class="float-right">
                                <a role="button" class="btn btn-sm btn-info"
                                   id="comment-{{ comment.pk }}-update-btn"
                                   href='/blog/update_comment/{{comment.pk}}/'>
                                    <small>edit</small>
                                </a>
                                <!-- 댓글 삭제하기 -->
                                <a role="button" class="btn btn-sm btn-danger"
                                   id="comment-{{ comment.pk }}-delete-modal-btn"
                                   href='/blog/delete_comment/{{comment.pk}}/'>
                                    <small>delete</small>
                            </a>
                            </div>
                            {% endif %}

                            <!-- 댓글 작성자랑 시간 남기기 -->
                            <div class="fw-bold"> {{ comment.author.username }} &nbsp;&nbsp;
                                <small class="text-muted">
                                    {{ comment.created_at }}
                                </small>
                            </div>
                            <div>
                                {{ comment.content | linebreaks }}
                            </div>
                            <!-- 댓글 수정하면 업데이트 시간 바꾸기 -->
                            {% if comment.created_at != comment.modified_at %}
                                <div class="text-muted float-right">
                                    <small>
                                        Updated: {{ comment.modified_at }}
                                    </small>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</section>

{% endblock %}

blog/templates/blog/post_form.html
    {% extends 'blog/base_full_width.html' %}

    {% load crispy_forms_tags %}

    {% block head_title %}Create Post - Blog{% endblock %}

    {% block main_content %}
        <h1>Create New Post</h1>
        <hr/>
        <form method="post" enctype="multipart/form-data">{% csrf_token %} <!--파일 첨부 있으면 enctype 있어야됨 파일 없으면 이거 없어도 ㄱㅊ-->
            <table>
                {{ form | crispy }}
            </table>
            <button type="submit" class="btn btn-primary float-right">Submit</button>
        </form>
    {% endblock %}

blog/templates/blog/post_update_form.html
    {% extends 'blog/base_full_width.html' %}

    {% load crispy_forms_tags %}

    {% block head_title %}Edit Post - Blog{% endblock %}

    {% block main_content %}
        <h1>Edit Post</h1>
        <hr/>
        <form method="post" enctype="multipart/form-data">{% csrf_token %} <!--파일 첨부 있으면 enctype 있어야됨 파일 없으면 이거 없어도 ㄱㅊ-->
                {{ form | crispy }}
            <button type="submit" class="btn btn-primary float-right">Submit</button>
        </form>
    {% endblock %}